sudo: required
services: 
  - docker

before_install:
  - docker build -t hongyuan010/yh-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t hongyuan010/multi-client ./client
  - docker build -t hongyuan010/multi-nginx ./nginx
  - docker build -t hongyuan010/multi-server ./server
  - docker build -t hongyuan010/multi-worker ./worker

