version: '3.8'
services:
  #name for the app not necessary to be web, can be anything
  web:
    build:
    # context tells compose where the dockerfile directory is 
    # "." means at the same direcotry 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3000"
    volumes:
      # not mapping app/node_modules
      - /app/node_modules
      # map current working directory "." 
      # to app folder. Sampe as Dockerfile.dev
      - "C:/GitRepos/yh-react:/app"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=true
    env_file:
      - ./environment.env