#To build a specified dockerfile run command as below
#Docker build -f Dockerfile.dev .
# Dont miss the '.' at the end.

FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD [ "npm", "start" ]
