# copy from dockerhub nginx. 
# NGINX is open source software for web serving, reverse proxying, caching, load balancing, media streaming, and more. 
# It started out as a web server designed for maximum performance and stability. 
# In addition to its HTTP server capabilities, NGINX can also function as a proxy server for email (IMAP, POP3, and SMTP) 
# and a reverse proxy and load balancer for HTTP, TCP, and UDP servers.
FROM nginx:1.15.8-alpine

COPY ./default.conf /etc/nginx/conf.d/default.conf

# COPY ./default.conf /etc/nginx/nginx.conf
